### ISSUE TITLE
Integrate with MiMa

### ISSUE THREAD

**Issue by DanSimon** [tumblr/colossus#506] opened 2017-03-15 16:27 UTC
[MiMa](https://github.com/typesafehub/migration-manager) is a SBT plugin that can help us detect binary incompatibility across builds.  This will be extremely helpful in ensuring that 0.n.x builds are binary compatible for all x, something we've been attempting to enforce but only as a guideline.

**Comment by DanSimon** [comment] 2017-08-15 14:24
Can you elaborate on using `sbt-release`?  What part of the existing build process would it replace/improve?

**Comment by aliyakamercan** [comment] 2017-08-15 21:18
I was thinking of making `mimaReportBinaryIssues`. However, I am not sure if that would be helpful. 

Besides that, I think replacing whole build process with `sbt-release` would be nice. Currently, everything is manual from tagging to publishing to maven central.

**Comment by DanSimon** [comment] 2017-08-15 21:48
Sounds like a pretty reasonable idea, as long as it can actually make things cleaner/more concise.  Two things though:

1.  Let's make that a separate issue from MiMa integration
2.  We also need to look at getting rid of `Build.scala` in general, since it's deprecated.  So maybe all of this can be wrapped into one larger "cleanup build process" task.

**Comment by benblack86** [comment] 2017-08-15 21:56
https://github.com/tumblr/colossus/issues/546
https://github.com/tumblr/colossus/issues/541

**Comment by nsauro** [comment] 2017-08-18 21:36
Howdy ya'll.

Need some help with this?  I've been doing a lot of SBT stuff lately, and can probably pitch in here.

**Comment by nsauro** [comment] 2017-08-18 21:36
In general, I've taken a pretty long hiatus from this project, mainly b/c I was super busy with other stuff, but I should start having more free time again, and would like to pitch in where i can.

**Comment by benblack86** [comment] 2017-08-19 01:54
Who hacked Nick's account?

**Comment by benblack86** [comment] 2017-08-21 16:21
Welcome back @nsauro. Do you want to look into this? Not sure we want to have it automatically error a build or just provide the information.

**Comment by benblack86** [comment] 2017-08-21 20:08
If you contribute can you also sign the CLA :) 

https://github.com/tumblr/colossus/blob/master/CONTRIBUTING.md

**Comment by nsauro** [comment] 2017-08-21 23:53
I can sign the CLA, though I might already have?  

So, which is more important? Mima or sbt-release?  If mima is a thing you want to use, do you want to use it during the release phase, or during compilation/tests?  

The one pain about Mima is tracking the previous versions you want to run mima against.  It would probably be less than ideal to go through sbt-release integration to avoid having to manually modify versions/tags/etc, only to then have to manually track previous versions.  What level of automation do you want around this?  We could probably do something around having mima read in previous versions from a file which is appended to at release time.  At least then we are automatically generating and using a list of released versions.  Removing from that list would be manual however.

**Comment by aliyakamercan** [comment] 2017-08-22 14:21
Hey @nsauro,

I recently merged #562, I think we will not use `sbt-release` for now. Maybe we can use `sbt-git` to get the latest version from the latest tag?

**Comment by nsauro** [comment] 2017-08-22 15:14
Out of curiosity, why not use sbt-release?  It really does trivialize the release process and is highly customizable.  For colossus, the only customizations you would need would be to replace publish, with publish-signed(at least at first glance :) ).  All of the tagging, git integration, etc is taken care of.  I believe you would need to make sure that travis can commit to colossus, so you might need to generate a key for that.

If you choose to use mima, you could then do it as part of the release process.  The one thing I'm struggling on, is this too late in the process for mima?

**Comment by aliyakamercan** [comment] 2017-08-22 18:05
After the latest changes, we can build, publish and release with pushing a version tag. 

`sbt-release` complicates travis-ci integration more. It will be harder to control versions, we will have to have some extra logic when we want something other than major version bump. We will have to skip commits back to master etc. I don't think we gain much from using it. 

I think release/publish step is a good place run mima, PRs can have non-binary compatible changes if they are going in a major release. Mima should only run for minor version bumps, probably before publish.

**Comment by benblack86** [comment] 2017-08-23 16:18
Might want to see what akka does since they seem to use MiMa: https://github.com/akka/akka/blob/master/CONTRIBUTING.md#binary-compatibility

**Comment by nsauro** [comment] 2017-08-24 00:56
Just a heads up.  I'm out of town until after Labor Day :)

**Comment by nsauro** [comment] 2017-08-28 17:11
So, I'm starting to poke around at this, and have it working at least in a very basic fashion.

What is the desired behavior here?

- Is this to be run manually during the deploy process?
- How do we want to populate the key `mimaPreviousArtifacts` which controls if the plugin is enabled for a project, and what previous versions to run against? To be controlled manually as well?  This would mean that at publish time, we would need to make sure this value is updated in the build.sbt.
- What updates (if any) to the travis build do you want?  To run this plugin based on a certain set of conditions?  Are the conditions that @aliyakamercan mentioned:
`
I think release/publish step is a good place run mima, PRs can have non-binary compatible changes if they are going in a major release. Mima should only run for minor version bumps, probably before publish.`
The only set of conditions?

**Comment by benblack86** [comment] 2017-08-28 19:53
Based on the new [CONTRIBUTING.md](https://github.com/tumblr/colossus/blob/develop/CONTRIBUTING.md), using the GitFlow model will mean we wouldn't publish that many minor builds - only if a hotfix is needed. Meaning this wouldn't actually be a problem. It might be nice to document the interface changes between x.y and x.Y+1 so it is easier for people to upgrade. Maybe we should just add it as a plugin, but leave it as something that is manually run when writing the release notes. Also we should write release notes :)

**Comment by nsauro** [comment] 2017-08-30 17:54
Ok, I will add this as a plugin, and should have something to go maybe by this evening.

**Comment by nsauro** [comment] 2017-08-31 00:51
So, I was getting ready to push a branch, and was looking at what I should set the value to for `mimaPreviousVersions`.  

I'm a bit confused.

The latest version in develop/master is `0.9.0-SNAPSHOT`, yet: a `0.9.1` exists in the wild

https://mvnrepository.com/artifact/com.tumblr/colossus_2.11

So my 2 questions are:
 - What should I set the previous builds to check mima against?
 - Is version tracking out of sync? Did we cut a release and forget to bump some versions?  Or am I just looking in the wrong place?

Are we following Semver?

**Comment by nsauro** [comment] 2017-08-31 00:52
Follow up question:
Are we following Semver?

**Comment by DanSimon** [comment] 2017-08-31 04:21
Oh yeah, develop should definitely be on `0.10.0-SNAPSHOT`, master should be on `0.9.2-SNAPSHOT`.

We're not doing semver in the strict sense that any breaking change causes a major version bump, for now we're still in 0.x versions.  But we are doing it for minor and hotfix versions.  So 0.10.0 and 0.11.0 need not be binary compatible, but 0.10.0 and 0.10.1 should be.

**Comment by benblack86** [comment] 2017-08-31 14:41
I think the problem is that version bumps previously happened in a branch that got reverted and hence didn't update master/develop.

**Comment by nsauro** [comment] 2017-09-01 17:51
I still think we should look into sbt-release, as that could potentially alleviate these kinds of issues.  However, gitflow would mean we would need a custom process in sbt-release, which isn't in itself, too bad, but does complicate any potential integration.  NBD for now.

So, for previous version, should I just use what is released right now?

**Comment by benblack86** [comment] 2017-09-01 17:55
Sure. If we use sbt-release, how will it work with travis?

**Comment by nsauro** [comment] 2017-09-01 18:10
I don't think it will, at least not easily.  At a side gig I once set up sbt-release with any commit to master that had a special tag in the message would kick off sbt-release.  It worked..mostly.  The biggest pain being that a commit to master was required..even if there was nothing that changed.  The travis.yml file here indicates that there is some level of determining if a release should be kicked off by travis via `publishSigned`.  That could be potentially swapped  to use `release with-defaults`, as a starting point.

I'm not super familiar with how colossus is released, as I've never done it, so I can't say for certain how good a fit this is..but I can say from experience, sbt-release does a great job of allowing for a repeatable, automated way to do release and all the clerical work(version bumps, tags, etc) involved.  Idk how involved we'd have to make the custom process to work with gitflow however.  Also depends on how much(if any) of the work you'd want to have sbt-release do.

**Comment by benblack86** [comment] 2017-09-01 18:48
Currently process is described here: https://github.com/tumblr/colossus/pull/562, basically a tag push to master.

**Comment by benblack86** [comment] 2017-09-07 15:23
https://github.com/tumblr/colossus/pull/583

**Closed by benblack86** 2017-09-07 15:23 UTC
Labels: enhancement
