### ISSUE TITLE
Upgrade Akka Version

### ISSUE THREAD

**Issue by nsauro** [tumblr/colossus#443] opened 2016-09-01 19:14 UTC
Hi guys! 👍 

I was wondering if you had any plans up bumping the Akka version to  the 2.4.x (preferably 2.4.9) :) ?  Might be somewhat of a big ask, since Akka 2.4.9 is only for Scala 2.11, so cross compiling back to 2.10 might be difficult.

Anyhow, I was considering bringing at least colossus-metrics onboard here, but the Akka version clashes might make for some fun run time issues :)

**Comment by DanSimon** [comment] 2016-09-02 16:18
Yeah I'd definitely like to get a build out on Akka 2.4/Java8.  I can take a look at creating a branch for doing such builds, but it probably won't be a "mainline" release for a while.

At some point we'll definitely be totally dropping 2.10 and adding 2.12 support, not sure on a timeline yet.

**Comment by DanSimon** [comment] 2016-09-07 14:52
Oh this is also a dupe of #372, so I'm going to close this.

**Closed by DanSimon** 2016-09-07 14:52 UTC
Labels: question
